language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
  - openjdk11

dist: trusty
sudo: required

install:
  - mvn dependency:get -Dartifact=org.yaml:snakeyaml:1.15

script:
  - mvn --batch-mode -q clean install
